#!/bin/bash
# ULTRATHINK CashMachine - Show Critical Rules

echo "==========================================="
echo "   🔴 REGRAS VERMELHAS - CASHMACHINE"
echo "==========================================="
echo ""
echo "1️⃣ TRABALHO EXCLUSIVO NA EC2:"
echo "   ❌ NUNCA criar arquivos localmente"
echo "   ❌ NUNCA modificar sistema local"
echo "   ❌ NUNCA ler arquivos locais sem permissão"
echo "   ❌ NUNCA fazer buscas/explorações locais"
echo "   ✅ SEMPRE trabalhar via SSM na EC2"
echo ""
echo "2️⃣ BLACK BOX - ISOLAMENTO TOTAL:"
echo "   ❌ ZERO acesso à internet"
echo "   ❌ Sem downloads externos"
echo "   ✅ Apenas VPC endpoints aprovados"
echo ""
echo "==========================================="
echo ""
echo "📍 WORKFLOW CORRETO:"
echo "1. aws ssm start-session --target i-0fdf66e20fe5c1bdb"
echo "2. cd /opt/cashmachine"
echo "3. Fazer TODO trabalho dentro da EC2"
echo ""
echo "🚨 EMERGÊNCIA:"
echo "aws ec2 stop-instances --instance-ids i-0fdf66e20fe5c1bdb --force"
echo ""
echo "==========================================="